/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.telas;

import br.ufrn.dimap.gui.ObjectViewer;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author leobrizolara
 */
public class Formulario extends javax.swing.JDialog implements ObjectViewer{
    private ObjectViewer editor;
    private Object obj;
    private boolean result; //usuario cancelou ou salvou?
    
    private List<ActionListener> actionListeners;
    
    public Formulario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        actionListeners = new ArrayList<>();
    }
    
    public void addActionListener(ActionListener listener){
        actionListeners.add(listener);
    }
    public void removeActionListener(ActionListener listener){
        actionListeners.remove(listener);
    }
    protected void fireActionListener(ActionEvent event){
       for(ActionListener listener : actionListeners){
           listener.actionPerformed(event);
       } 
    }
    
    public ObjectViewer getViewer() {
        return editor;
    }

    public void setViewer(ObjectViewer viewer) {
        this.editor = viewer;
        this.pnlDados.removeAll();
        if(viewer != null){
            pnlDados.add(viewer.getView());
            
            if(obj!= null){
                viewer.setObject(obj);
            }
        }
        this.revalidate();
        this.repaint();
    }
    
    public void setObject(Object object) {
        this.obj = object;
        if(editor != null){
            editor.setObject(object);
            
            this.revalidate();
            this.repaint(); 
        }
    }

    public Object getObject() {
        if(editor != null){
            obj = editor.getObject();
        }
        return obj;
    }

    public Component getView() {
        return this;
    }

    public Class getObjectClass() {
        if(getObject() != null){
            getObject().getClass();
        }
        return Object.class;
    }

    
    private void doCancel() {
        this.setResult(false);
        fireActionListener(new ActionEvent(this, 0, "Cancel"));
        this.setVisible(false);
    }
    private void doSave() {
        this.setResult(true);
        fireActionListener(new ActionEvent(this, 1, "Save"));
        this.setVisible(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbarButtons = new javax.swing.JToolBar();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        scpDados = new javax.swing.JScrollPane();
        pnlDados = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbarButtons.setRollover(true);

        btnSave.setText("Save");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        tbarButtons.add(btnSave);

        btnCancel.setText("Cancel");
        btnCancel.setFocusable(false);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        tbarButtons.add(btnCancel);

        getContentPane().add(tbarButtons, java.awt.BorderLayout.PAGE_END);

        scpDados.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scpDados.setViewportView(pnlDados);

        getContentPane().add(scpDados, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.doCancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        this.doSave();
    }//GEN-LAST:event_btnSaveActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JScrollPane scpDados;
    private javax.swing.JToolBar tbarButtons;
    // End of variables declaration//GEN-END:variables

    public boolean isResult() {
        return result;
    }

    public void setResult(boolean result) {
        this.result = result;
    }
}
