/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.telas;

import br.ufrn.dimap.gui.NavigationEvent;
import br.ufrn.dimap.gui.controladores.DisciplinaCRUD;
import br.ufrn.dimap.gui.controladores.TurmaCRUD;

/**
 *
 * @author leobrizolara
 */
public class TelaHome extends Tela{
    public TelaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAlunos = new javax.swing.JButton();
        btnDocentes = new javax.swing.JButton();
        btnTurmas = new javax.swing.JButton();
        btnBancasExaminadoras = new javax.swing.JButton();
        btnGerenciarTurmas = new javax.swing.JButton();
        btnGerenciarDisciplinas = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        btnAlunos.setText("Alunos");
        btnAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunosActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlunos);

        btnDocentes.setText("Docentes");
        btnDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocentesActionPerformed(evt);
            }
        });
        jPanel1.add(btnDocentes);

        btnTurmas.setText("Turmas");
        btnTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurmasActionPerformed(evt);
            }
        });
        jPanel1.add(btnTurmas);

        btnBancasExaminadoras.setText("Bancas Examinadoras");
        btnBancasExaminadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBancasExaminadorasActionPerformed(evt);
            }
        });
        jPanel1.add(btnBancasExaminadoras);

        btnGerenciarTurmas.setText("Gerenciar Turmas");
        btnGerenciarTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarTurmasActionPerformed(evt);
            }
        });
        jPanel1.add(btnGerenciarTurmas);

        btnGerenciarDisciplinas.setText("Gerenciar Disciplinas");
        btnGerenciarDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarDisciplinasActionPerformed(evt);
            }
        });
        jPanel1.add(btnGerenciarDisciplinas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunosActionPerformed
        this.fireNavigate("TelaVisualizarAlunos");
    }//GEN-LAST:event_btnAlunosActionPerformed

    private void btnDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocentesActionPerformed
        this.fireNavigate("TelaVisualizarDocentes");
    }//GEN-LAST:event_btnDocentesActionPerformed

    private void btnTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurmasActionPerformed
        this.fireNavigate("TelaVisualizarTurmas");
    }//GEN-LAST:event_btnTurmasActionPerformed

    private void btnBancasExaminadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBancasExaminadorasActionPerformed
        this.fireNavigate("TelaVisualizarBancasExaminadoras");
    }//GEN-LAST:event_btnBancasExaminadorasActionPerformed

    private void btnGerenciarTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarTurmasActionPerformed
        NavigationEvent naviEvent = new NavigationEvent(this, "TelaGerenciar");
        naviEvent.addArg("Controle", new TurmaCRUD());
        this.fireNavigate(naviEvent);
    }//GEN-LAST:event_btnGerenciarTurmasActionPerformed

    private void btnGerenciarDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarDisciplinasActionPerformed
        NavigationEvent naviEvent = new NavigationEvent(this, "TelaGerenciar");
        naviEvent.addArg("Controle", new DisciplinaCRUD());
        this.fireNavigate(naviEvent);
    }//GEN-LAST:event_btnGerenciarDisciplinasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlunos;
    private javax.swing.JButton btnBancasExaminadoras;
    private javax.swing.JButton btnDocentes;
    private javax.swing.JButton btnGerenciarDisciplinas;
    private javax.swing.JButton btnGerenciarTurmas;
    private javax.swing.JButton btnTurmas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
