/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.telas;

import br.ufrn.dimap.gui.NavigationEvent;
import br.ufrn.dimap.entidades.Docente;
import br.ufrn.dimap.gui.ItemSelectionEvent;
import br.ufrn.dimap.gui.ItemSelectionListener;
import br.ufrn.dimap.gui.widgets.ObjectListView;
import br.ufrn.dimap.gui.widgets.VinculoViewerResumo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collection;

/**
 *
 * @author leobrizolara
 */
public class TelaVisualizarDocentes extends Tela implements ItemSelectionListener {
    Collection<? extends Object> docentes;
    /**
     * Creates new form TelaVisaoDocentes
     */
    public TelaVisualizarDocentes(){
        this(new ArrayList<Docente>());
    }
    public TelaVisualizarDocentes(Collection<Docente> docentes) {
        this.docentes = docentes; 
        initComponents();
        
        this.lstDocentes.addItemSelectionListener(this);
    }

    
    public void itemSelected(ItemSelectionEvent event) {
        if(event.getSelectedItem() instanceof Docente){
            this.showDocente((Docente) event.getSelectedItem());
        }
    }
    private void showDocente(Docente docente) {
        NavigationEvent event = new NavigationEvent(this, "TelaVisualizarDadosDocente");
        event.addArg("Docente", docente);
        this.fireNavigate(event);
    }
    
    private ObjectListView  criarListaDeDocentes(){
        if(docentes == null){
            return new ObjectListView(new VinculoViewerResumo());
        }
        else{
            return new ObjectListView(new VinculoViewerResumo(),docentes);
        }
    }
    
    public void setDocentes(Collection<Docente> docentes){
        this.docentes = docentes;
        this.lstDocentes.setCollection(docentes);
    }
    public Collection<Docente> getDocentes(){
        return (Collection<Docente>) this.docentes;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrDocentes = new javax.swing.JScrollPane();
        lstDocentes = criarListaDeDocentes();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        scrDocentes.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        lstDocentes.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        scrDocentes.setViewportView(lstDocentes);

        add(scrDocentes);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.ufrn.dimap.gui.widgets.ObjectListView lstDocentes;
    private javax.swing.JScrollPane scrDocentes;
    // End of variables declaration//GEN-END:variables

}
