/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.telas;

import br.ufrn.dimap.entidades.Agrupamento;
import br.ufrn.dimap.entidades.MatriculaAlunoTurma;
import br.ufrn.dimap.entidades.Turma;
import br.ufrn.dimap.gui.ItemSelectionEvent;
import br.ufrn.dimap.gui.ItemSelectionListener;
import br.ufrn.dimap.gui.NavigationEvent;
import br.ufrn.dimap.gui.ObjectViewer;
import br.ufrn.dimap.gui.widgets.AlunoTurmaViewer;
import br.ufrn.dimap.gui.widgets.TurmaAlunoViewer;
import br.ufrn.dimap.gui.widgets.VinculoViewerResumo;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Collection;

/**
 *
 * @author leobrizolara
 */
public class TelaVisualizarDadosTurma extends Tela implements ObjectViewer, ItemSelectionListener {
    Turma turma;
    Agrupamento agrupamentoAlunos;
    private Collection<? extends Object> alunosTurma;
    /**
     * Creates new form TelaVisualizarDadosTurma
     */
    public TelaVisualizarDadosTurma() {
        this(new Turma());
    }

    TelaVisualizarDadosTurma(Turma turma) {
        this(turma, new ArrayList<MatriculaAlunoTurma>());
        
    }
    TelaVisualizarDadosTurma(Turma turma, Collection<MatriculaAlunoTurma> alunosTurma) {
        initComponents();
        
        this.lstDocentes.setViewer(new VinculoViewerResumo());
        
        this.setObject(turma);
        
        this.tableAgrupamentoAlunos.addItemSelectionListener(this);
        
        agrupamentoAlunos = new Agrupamento("Alunos");
        this.alunosTurma = alunosTurma;
        this.tableAgrupamentoAlunos.setElementView(new AlunoTurmaViewer());
        this.agrupar();
    }

    
    public void setObject(Object obj) {
        if(obj instanceof Turma){
            this.turma = (Turma)obj;
            if(turma.getDisciplina() != null){
                this.lblDisciplinaValor.setText(turma.getDisciplina().getNome());
            }
            
            this.lblPeriodoValor.setText(turma.getPeriodoLetivo());
            this.lblTurmaNumValor.setText(Integer.toString(turma.getNumeroTurma()));
            
            this.lblHorarioValor.setText(turma.getCodHorarioDeAula());
            this.lblLocalDeAulaValor.setText(turma.getLocalDeAula());
            
            this.lblStatusValor.setText(turma.getStatus());
            if(this.turma.getDocentes() != null){
                this.lstDocentes.setCollection((Collection<? extends Object>) turma.getDocentes());
            }
        }
    }

    public Object getObject() {
        return this.turma;
    }

    public Component getView() {
        return this;
    }

    public Class getObjectClass() {
        return Turma.class;
    }

    public Collection<MatriculaAlunoTurma> getAlunosTurma() {
        return (Collection<MatriculaAlunoTurma>) alunosTurma;
    }

    public void setAlunosTurma(Collection<MatriculaAlunoTurma> alunosTurma) {
        this.alunosTurma = alunosTurma;
        agrupar();
    }

    private void agrupar() {//TODO: adicionar novas formas de agrupamento?
        if(alunosTurma != null){
            agrupamentoAlunos = new Agrupamento("Alunos");
            for(Object obj : alunosTurma){
                if(obj instanceof MatriculaAlunoTurma){
                    this.agrupamentoAlunos.addItem("Alunos", obj);
                }
            }
            this.tableAgrupamentoAlunos.setAgrupamento(agrupamentoAlunos);
        }
    }
    
    public void itemSelected(ItemSelectionEvent event) {
        if(event.getSelectedItem() instanceof MatriculaAlunoTurma){
            NavigationEvent eventNavi = new NavigationEvent(this, "TelaVisualizarDadosAluno");
            eventNavi.addArg("Aluno", ((MatriculaAlunoTurma)event.getSelectedItem()).getAluno());
            this.fireNavigate(eventNavi);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlGlobal = new javax.swing.JPanel();
        pnlDadosTurma = new javax.swing.JPanel();
        lblDisciplinaValor = new javax.swing.JLabel();
        lblPeriodoValor = new javax.swing.JLabel();
        lblTurmaNumLabel = new javax.swing.JLabel();
        lblTurmaNumValor = new javax.swing.JLabel();
        lblHorarioLabel = new javax.swing.JLabel();
        lblHorarioValor = new javax.swing.JLabel();
        lblLocalDeAulaLabel = new javax.swing.JLabel();
        lblLocalDeAulaValor = new javax.swing.JLabel();
        lblStatusLabel = new javax.swing.JLabel();
        lblStatusValor = new javax.swing.JLabel();
        pnlDocentes = new javax.swing.JPanel();
        lblDocentesLabel = new javax.swing.JLabel();
        scpDocentes = new javax.swing.JScrollPane();
        lstDocentes = new br.ufrn.dimap.gui.widgets.ObjectListView();
        pnlAlunos = new javax.swing.JPanel();
        scpAlunos = new javax.swing.JScrollPane();
        tableAgrupamentoAlunos = new br.ufrn.dimap.gui.widgets.TableAgrupamentoViewer();
        lblAlunosLabel = new javax.swing.JLabel();

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        lblDisciplinaValor.setFont(lblDisciplinaValor.getFont().deriveFont(lblDisciplinaValor.getFont().getSize()+4f));
        lblDisciplinaValor.setText("<Disciplina>");

        lblPeriodoValor.setFont(lblPeriodoValor.getFont().deriveFont(lblPeriodoValor.getFont().getSize()+2f));
        lblPeriodoValor.setText("<período>");

        lblTurmaNumLabel.setText("Turma:");

        lblTurmaNumValor.setText("<nº turma>");

        lblHorarioLabel.setText("Horário de aula:");

        lblHorarioValor.setText("<horario>");

        lblLocalDeAulaLabel.setText("Local de aula:");

        lblLocalDeAulaValor.setText("<local de aula>");

        lblStatusLabel.setText("Status:");

        lblStatusValor.setText("<status>");

        javax.swing.GroupLayout pnlDadosTurmaLayout = new javax.swing.GroupLayout(pnlDadosTurma);
        pnlDadosTurma.setLayout(pnlDadosTurmaLayout);
        pnlDadosTurmaLayout.setHorizontalGroup(
            pnlDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosTurmaLayout.createSequentialGroup()
                        .addComponent(lblDisciplinaValor)
                        .addGap(18, 18, 18)
                        .addComponent(lblPeriodoValor))
                    .addGroup(pnlDadosTurmaLayout.createSequentialGroup()
                        .addComponent(lblHorarioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHorarioValor)
                        .addGap(18, 18, 18)
                        .addComponent(lblLocalDeAulaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLocalDeAulaValor))
                    .addGroup(pnlDadosTurmaLayout.createSequentialGroup()
                        .addComponent(lblStatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStatusValor))
                    .addGroup(pnlDadosTurmaLayout.createSequentialGroup()
                        .addComponent(lblTurmaNumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTurmaNumValor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDadosTurmaLayout.setVerticalGroup(
            pnlDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisciplinaValor)
                    .addComponent(lblPeriodoValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTurmaNumLabel)
                    .addComponent(lblTurmaNumValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorarioLabel)
                    .addComponent(lblHorarioValor)
                    .addComponent(lblLocalDeAulaLabel)
                    .addComponent(lblLocalDeAulaValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatusLabel)
                    .addComponent(lblStatusValor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDocentes.setLayout(new java.awt.BorderLayout());

        lblDocentesLabel.setText("Docentes:");
        pnlDocentes.add(lblDocentesLabel, java.awt.BorderLayout.NORTH);

        scpDocentes.setViewportView(lstDocentes);

        pnlDocentes.add(scpDocentes, java.awt.BorderLayout.CENTER);

        pnlAlunos.setLayout(new java.awt.BorderLayout());

        scpAlunos.setViewportView(tableAgrupamentoAlunos);

        pnlAlunos.add(scpAlunos, java.awt.BorderLayout.CENTER);

        lblAlunosLabel.setText("Alunos:");
        pnlAlunos.add(lblAlunosLabel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout pnlGlobalLayout = new javax.swing.GroupLayout(pnlGlobal);
        pnlGlobal.setLayout(pnlGlobalLayout);
        pnlGlobalLayout.setHorizontalGroup(
            pnlGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDadosTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDocentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlGlobalLayout.setVerticalGroup(
            pnlGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDadosTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlGlobal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlunosLabel;
    private javax.swing.JLabel lblDisciplinaValor;
    private javax.swing.JLabel lblDocentesLabel;
    private javax.swing.JLabel lblHorarioLabel;
    private javax.swing.JLabel lblHorarioValor;
    private javax.swing.JLabel lblLocalDeAulaLabel;
    private javax.swing.JLabel lblLocalDeAulaValor;
    private javax.swing.JLabel lblPeriodoValor;
    private javax.swing.JLabel lblStatusLabel;
    private javax.swing.JLabel lblStatusValor;
    private javax.swing.JLabel lblTurmaNumLabel;
    private javax.swing.JLabel lblTurmaNumValor;
    private br.ufrn.dimap.gui.widgets.ObjectListView lstDocentes;
    private javax.swing.JPanel pnlAlunos;
    private javax.swing.JPanel pnlDadosTurma;
    private javax.swing.JPanel pnlDocentes;
    private javax.swing.JPanel pnlGlobal;
    private javax.swing.JScrollPane scpAlunos;
    private javax.swing.JScrollPane scpDocentes;
    private br.ufrn.dimap.gui.widgets.TableAgrupamentoViewer tableAgrupamentoAlunos;
    // End of variables declaration//GEN-END:variables

}
