/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.telas;

import br.ufrn.dimap.entidades.Agrupamento;
import br.ufrn.dimap.gui.ItemSelectionEvent;
import br.ufrn.dimap.gui.ItemSelectionListener;
import br.ufrn.dimap.gui.NavigationEvent;
import br.ufrn.dimap.gui.ObjectViewer;
import java.util.Collection;
import javax.swing.JOptionPane;

/**
 *
 * @author leobrizolara
 */
public class TelaGerenciar extends Tela implements ItemSelectionListener{
    private Collection<? extends Object> collection;
    
    public TelaGerenciar() {
        initComponents();
        
        this.objectListView1.addItemSelectionListener(this);
    }
    
    public Collection<? extends Object> getCollection() {
        return collection;
    }
    public void setCollection(Collection<? extends Object> collection) {
        this.collection = collection;
        this.objectListView1.setCollection(collection);
    }
    public void addItem(Object item){
        this.objectListView1.addElement(item);
    }
    public void removeItem(Object item){
        this.objectListView1.removeElement(item);
    }
    
    public void setElementViewer(ObjectViewer viewer){
        this.objectListView1.setViewer(viewer);
    }
    public ObjectViewer getElementViewer(){
        return this.objectListView1.getViewer();
    }
    
    
    private void criarNovo(){
        this.fireNavigate("Novo");        
    }

    private void editar() {
        NavigationEvent naviEvent = new NavigationEvent(this, "Editar");
        naviEvent.addArg("Item", this.objectListView1.getSelectedValue());
        this.fireNavigate(naviEvent); 
    }

    private void excluir() {
        Object selected = this.objectListView1.getSelectedValue();
        if(selected != null){
            int response = JOptionPane.showConfirmDialog(this, "Excluir " + selected.toString() + " ?");

            if(response == JOptionPane.YES_OPTION){
                NavigationEvent naviEvent = new NavigationEvent(this, "Excluir");
                naviEvent.addArg("Item", this.objectListView1.getSelectedValue());
                this.fireNavigate(naviEvent); 
                
                this.objectListView1.removeElement(selected);
            }
        }
    }

    @Override
    public void itemSelected(ItemSelectionEvent event) {
        if(event.getSelectedItem() != null && event.getSource() == this.objectListView1){
            //TODO: garantir q este é o item selecionado
            
            this.editar();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        objectListView1 = new br.ufrn.dimap.gui.widgets.ObjectListView();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNovo);

        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);

        btnExcluir.setText("Excluir");
        btnExcluir.setFocusable(false);
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluir);

        add(jToolBar1, java.awt.BorderLayout.NORTH);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jScrollPane2.setViewportView(objectListView1);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.criarNovo();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.editar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        this.excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private br.ufrn.dimap.gui.widgets.ObjectListView objectListView1;
    // End of variables declaration//GEN-END:variables

}
