/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import br.ufrn.dimap.dataAccess.AlunoDAO;
import br.ufrn.dimap.dataAccess.DatabaseController;
import br.ufrn.dimap.dataAccess.DocenteDAO;
import br.ufrn.dimap.dataAccess.MySqlDatabaseController;
import br.ufrn.dimap.dataAccess.PublicacaoDAO;
import br.ufrn.dimap.dataAccess.TurmaDAO;
import br.ufrn.dimap.entidades.Docente;
import br.ufrn.dimap.entidades.Turma;
import br.ufrn.dimap.gui.telas.Navigable;
import br.ufrn.dimap.gui.telas.TelaVisualizarAlunos;
import br.ufrn.dimap.gui.telas.TelaVisualizarDocentes;
import br.ufrn.dimap.gui.telas.TelaVisualizarDadosDocente;
import br.ufrn.dimap.gui.telas.TelaVisualizarTurmas;
import java.awt.Container;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author leobrizolara
 */
public class FrameTeste extends javax.swing.JFrame implements Navigable {
    DatabaseController dataManager;
    Collection<? extends Object> alunos;
    Collection<? extends Object> turmas;
    /**
     * Creates new form appJFfame
     */
    public FrameTeste() {
        try {
            UIManager.setLookAndFeel(
                UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            ex.printStackTrace();
            Logger.getLogger(FrameTeste.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            dataManager = new MySqlDatabaseController("jdbc:mysql://localhost/dbPosGraduacao", "root","root");        }
        catch(ClassNotFoundException e){
            e.printStackTrace();
            System.exit(1);
        }
        
        AlunoDAO alunoDAO = new AlunoDAO(dataManager);
        this.alunos = alunoDAO.listAll();
        
        TurmaDAO turmaDAO = new TurmaDAO(dataManager);
        this.turmas = turmaDAO.listAll();
        
        
        DocenteDAO docentesDAO = new DocenteDAO(dataManager);
        Collection<Docente> docentes = (Collection<Docente>) docentesDAO.listAll();
        
        initComponents();
        this.telaVisaoDocentes2.setNavigableParent(this);
             
        this.telaVisualizarAlunos1.setAlunos(alunos);
        //this.newJPanel1.setAlunos(alunos);
        
        this.telaVisualizarTurmas1.setTurmas((Collection<Turma>) turmas);
        
        this.telaVisaoDocentes2.setDocentes(docentes);
        
        this.telaVisualizarDadosTurma1.setObject(turmas.toArray()[0]);
    }
    
    
    public void navigate(Object source, Container tela) {
        System.out.println("navigate");
        
        if(tela instanceof TelaVisualizarDadosDocente){
            TelaVisualizarDadosDocente telaDadosDocente = (TelaVisualizarDadosDocente)tela;
        
            if(telaDadosDocente.getDocente() != null)
            {
                Docente docente = telaDadosDocente.getDocente();
                TurmaDAO turmasDAO = new TurmaDAO(dataManager);                
                telaDadosDocente.setTurmasDocente((Collection<Turma>) turmasDAO.search(docente));
 
                PublicacaoDAO publicacaoDAO = new PublicacaoDAO(dataManager);
                telaDadosDocente.setPublicacoesDocente(publicacaoDAO.search(docente.getPessoa()));
                
                this.remove(this.telaVisaoDocentes2);
                this.add(telaDadosDocente);
                
                this.pack();
            }
        }
    }

    
    TelaVisualizarDadosDocente gerarTelaDocentes(){
            TurmaDAO turmasDAO = new TurmaDAO(dataManager);
            Collection<Object> turmas = (Collection<Object>) turmasDAO.listAll();
            
            Docente createdDocente = new Docente();
            
            TelaVisualizarDadosDocente panel = new TelaVisualizarDadosDocente(createdDocente, turmas);
            
            return panel;
        
    }
//    TelaVisualizarDocentes criarTelaDocentes(){
//            DocenteDAO docentesDAO = new DocenteDAO(dataManager);
//            Collection<Docente> docente = (Collection<Docente>) docentesDAO.listAll();
//                        
//            return new TelaVisualizarDocentes(docente);
//        
//    }
    TelaVisualizarDocentes criarTelaDocentes(){                        
            return new TelaVisualizarDocentes();
        
    }
    TelaVisualizarAlunos criarTelaAlunos(){
//        AlunoDAO alunoDAO = new AlunoDAO(dataManager);
//        Collection<? extends Object> alunos = alunoDAO.listAll();
//        
//        return new TelaVisualizarAlunos(alunos);
        return new TelaVisualizarAlunos();
    }
    
    private TelaVisualizarTurmas criarTelaVisualizarTurmas(){
        return new TelaVisualizarTurmas();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        telaVisaoDocentes2 = criarTelaDocentes();
        telaVisualizarAlunos1 = criarTelaAlunos();
        telaVisualizarTurmas1 = criarTelaVisualizarTurmas();
        telaVisualizarDadosTurma1 = new br.ufrn.dimap.gui.telas.TelaVisualizarDadosTurma();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jTabbedPane1.addTab("tab1", telaVisaoDocentes2);
        jTabbedPane1.addTab("tab2", telaVisualizarAlunos1);
        jTabbedPane1.addTab("tab4", telaVisualizarTurmas1);
        jTabbedPane1.addTab("tab5", telaVisualizarDadosTurma1);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTeste().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private br.ufrn.dimap.gui.telas.TelaVisualizarDocentes telaVisaoDocentes2;
    private br.ufrn.dimap.gui.telas.TelaVisualizarAlunos telaVisualizarAlunos1;
    private br.ufrn.dimap.gui.telas.TelaVisualizarDadosTurma telaVisualizarDadosTurma1;
    private br.ufrn.dimap.gui.telas.TelaVisualizarTurmas telaVisualizarTurmas1;
    // End of variables declaration//GEN-END:variables

}
