/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.telas;

import br.ufrn.dimap.entidades.Agrupamento;
import br.ufrn.dimap.entidades.BancaExaminadora;
import br.ufrn.dimap.gui.ItemSelectionEvent;
import br.ufrn.dimap.gui.ItemSelectionListener;
import br.ufrn.dimap.gui.NavigationEvent;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Date;
import javax.swing.JComboBox;




/**
 *
 * @author leobrizolara
 */
public class TelaVisualizarBancasExaminadoras extends Tela implements ItemSelectionListener{
    
    enum TipoAgrupamento{
        TODOS, REALIZADAS
    }


    Collection<? extends Object> bancas;
    TipoAgrupamento agrupamentoAtual;
    /**
     * Creates new form TelaVisualizarBancasExaminadoras
     */
    public TelaVisualizarBancasExaminadoras() {
        initComponents();
        agrupamentoAtual = TipoAgrupamento.TODOS;
        this.cmbTiposAgrupamento.addItem(TipoAgrupamento.TODOS);
        this.cmbTiposAgrupamento.addItem(TipoAgrupamento.REALIZADAS);
        
        this.tblAgrupamentoBancasViewer.addItemSelectionListener(this);
    }
    public TelaVisualizarBancasExaminadoras(Collection<? extends Object> bancas) {
        this();//chama construtor sem parametros
        this.setBancasExaminadoras(bancas);
    }

    
    public void itemSelected(ItemSelectionEvent event) {
        
        if(event.getSelectedItem() instanceof BancaExaminadora){
            NavigationEvent naviEvent = new NavigationEvent(this, "TelaVisualizarDadosBancaExaminadora");
            naviEvent.addArg("BancaExaminadora", event.getSelectedItem());
            
            this.fireNavigate(naviEvent);
        }
    }
    
    public void setBancasExaminadoras(Collection<? extends Object> bancas){
        this.bancas = bancas;
        this.agrupamentoAtual = TipoAgrupamento.TODOS;
        this.agrupar();
        
        //this.setTipoAgrupamento(TipoAgrupamento.TODOS);
        //this.tableAgrupamentoListViewer1.setAgrupamento(criarAgrupamentoTodos());
        //this.lstBancaExaminadoras.setCollection(bancas);
    }
    public Collection<? extends Object> getBancasExaminadoras(){
        return this.bancas;
    }
    
    
    public void setTipoAgrupamento(TipoAgrupamento tipoAgrupamento) {
        if(this.agrupamentoAtual != tipoAgrupamento){
            this.agrupamentoAtual = tipoAgrupamento;
            this.agrupar();
        }
    }
    public TipoAgrupamento getTipoAgrupamento(){
        return this.agrupamentoAtual;
    }
    private void agrupar() {
        Agrupamento agrupamento;
        switch(agrupamentoAtual){
            case TODOS:
                agrupamento = criarAgrupamentoTodos();
                break;
            case REALIZADAS:
                agrupamento = criarAgrupamentoPorRealizacao();
                break;
            default:
                throw new AssertionError(agrupamentoAtual.name());
        }
        this.tblAgrupamentoBancasViewer.setAgrupamento(agrupamento);
    }
    private Agrupamento criarAgrupamentoTodos() {
        Agrupamento agrupamento = new Agrupamento("BancasExaminadoras");
        agrupamento.setCategoria("BancasExaminadoras", bancas);
        
        return agrupamento;
    }
    private Agrupamento criarAgrupamentoPorRealizacao() {
        Agrupamento agrupamento = new Agrupamento("Bancas Examinadoras por realização");
        
        for(Object o : bancas){
            if(o instanceof BancaExaminadora){
                BancaExaminadora banca = (BancaExaminadora)o;
                
                agrupamento.addItem(
                    (banca.getDataDeDefesa().before(new Date()) ? "Realizadas" : "Marcadas"), banca);
            }
        }
        
        return agrupamento;    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lblTipoAgrupamento = new javax.swing.JLabel();
        cmbTiposAgrupamento = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgrupamentoBancasViewer = new br.ufrn.dimap.gui.widgets.TableAgrupamentoViewer();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        lblTipoAgrupamento.setText("Agrupamento:");
        jToolBar1.add(lblTipoAgrupamento);

        cmbTiposAgrupamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTiposAgrupamentoActionPerformed(evt);
            }
        });
        jToolBar1.add(cmbTiposAgrupamento);

        add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setViewportView(tblAgrupamentoBancasViewer);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTiposAgrupamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTiposAgrupamentoActionPerformed
        JComboBox comboBox = (JComboBox) evt.getSource();
        if(comboBox.getSelectedItem() instanceof TipoAgrupamento){
            this.setTipoAgrupamento((TipoAgrupamento) comboBox.getSelectedItem());
        }
    }//GEN-LAST:event_cmbTiposAgrupamentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbTiposAgrupamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblTipoAgrupamento;
    private br.ufrn.dimap.gui.widgets.TableAgrupamentoViewer tblAgrupamentoBancasViewer;
    // End of variables declaration//GEN-END:variables

}
