/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.telas;

import br.ufrn.dimap.entidades.Turma;
import br.ufrn.dimap.gui.widgets.ObjectViewer;
import br.ufrn.dimap.gui.widgets.VinculoViewerResumo;
import java.awt.Component;
import java.util.Collection;

/**
 *
 * @author leobrizolara
 */
public class TelaVisualizarDadosTurma extends javax.swing.JPanel implements ObjectViewer {
    Turma turma;
    /**
     * Creates new form TelaVisualizarDadosTurma
     */
    public TelaVisualizarDadosTurma() {
        initComponents();
        
        this.objectListView1.setViewer(new VinculoViewerResumo());
    }

    TelaVisualizarDadosTurma(Turma turma) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDisciplinaValor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        objectListView1 = new br.ufrn.dimap.gui.widgets.ObjectListView();

        jLabel1.setText("Disciplina:");

        lblDisciplinaValor.setText("<disciplina>");

        jLabel3.setText("Docentes:");

        jScrollPane1.setViewportView(objectListView1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDisciplinaValor))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblDisciplinaValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDisciplinaValor;
    private br.ufrn.dimap.gui.widgets.ObjectListView objectListView1;
    // End of variables declaration//GEN-END:variables

    public void setObject(Object obj) {
        if(obj instanceof Turma){
            this.turma = (Turma)obj;
            if(turma.getDisciplina() != null){
                this.lblDisciplinaValor.setText(turma.getDisciplina().getNome());
            }
            this.objectListView1.setCollection((Collection<? extends Object>) turma.getDocentes());
//            turma.getCodHorarioDeAula();
//            turma.getDisciplina();
//            turma.getDocentes();
//            turma.getLocalDeAula();
//            turma.getNumeroTurma();
//            turma.getPeriodoLetivo();
//            turma.getStatus();
            
            //atualizar a IU
        }
    }

    public Object getObject() {
        return this.turma;
    }

    public Component getView() {
        return this;
    }

    public Class getObjectClass() {
        return Turma.class;
    }
}
