/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.telas;

import br.ufrn.dimap.entidades.Docente;
import br.ufrn.dimap.gui.widgets.ObjectListView;
import br.ufrn.dimap.gui.widgets.VinculoViewerResumo;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collection;

/**
 *
 * @author leobrizolara
 */
public class TelaVisualizarDocentes extends javax.swing.JPanel implements ActionListener {
    Collection<? extends Object> docentes;
    Navigable parent;
    /**
     * Creates new form TelaVisaoDocentes
     */
    public TelaVisualizarDocentes(){
        this(new ArrayList<Docente>());
    }
    public TelaVisualizarDocentes(Collection<Docente> docentes) {
        this.docentes = docentes; 
        initComponents();
        
        this.lstDocentes.addActionListener(this);
    }
    
    public void setNavigableParent(Navigable parent){
        this.parent = parent;
    }
    public Navigable getNavigableParent(){
        return parent;
    }

    private void showDocente(Docente docente) {
        if(parent != null){
            parent.navigate(this, (Container)new TelaVisualizarDadosDocente(docente, null));
        }
    }
    public void actionPerformed(ActionEvent ae) {
        System.out.print(ae.getSource() + " - ");
        System.out.println(ae.getActionCommand());
        
        if(ae.getSource() instanceof Docente ){
            this.showDocente((Docente)ae.getSource());
        }
    }
    
    private ObjectListView  criarListaDeDocentes(){
        if(docentes == null){
            return new ObjectListView(new VinculoViewerResumo());
        }
        else{
            return new ObjectListView(new VinculoViewerResumo(),docentes);
        }
    }
    
    public void setDocentes(Collection<Docente> docentes){
        this.docentes = docentes;
        this.lstDocentes.setCollection(docentes);
    }
    public Collection<Docente> getDocentes(){
        return (Collection<Docente>) this.docentes;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrDocentes = new javax.swing.JScrollPane();
        lstDocentes = criarListaDeDocentes();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        lstDocentes.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        scrDocentes.setViewportView(lstDocentes);

        add(scrDocentes);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.ufrn.dimap.gui.widgets.ObjectListView lstDocentes;
    private javax.swing.JScrollPane scrDocentes;
    // End of variables declaration//GEN-END:variables

}
