/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.telas;

import br.ufrn.dimap.entidades.Disciplina;
import br.ufrn.dimap.entidades.Docente;
import br.ufrn.dimap.entidades.Turma;
import br.ufrn.dimap.gui.widgets.ObjectListView;
import br.ufrn.dimap.gui.widgets.TurmaViewer;
import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JList;

/**
 *
 * @author leobrizolara
 */
public class TelaVisualizarDadosDocente extends javax.swing.JPanel {    
    Docente docente;
    Collection<? extends Object> historicoDeTurmas;
    Collection<? extends Object> publicacoesDocente;
    
    public TelaVisualizarDadosDocente() {
        this(new Docente(), null); //TODO: retirar isso
    }
    
    public TelaVisualizarDadosDocente(Docente docente, Collection<? extends Object> turmasMinistradas){    
        initComponents();
        this.viewDadosPessoais1.setObject(docente);
        this.docente = docente;
        this.setTurmasDocente(turmasMinistradas);
    }

    public void setTurmasDocente(Collection<? extends Object> TurmasDocente){
        if(TurmasDocente == null){
            historicoDeTurmas = new ArrayList<Turma>();
        }
        else{
            historicoDeTurmas = TurmasDocente;
        }
        this.objectListView1.setCollection(historicoDeTurmas);
    }
    public Collection<? extends Object> getTurmasDocente(){
        return this.historicoDeTurmas;
    }
    
    public void setPublicacoesDocente(Collection<? extends Object> publicacoes){
        if(publicacoes == null){
            this.publicacoesDocente = new ArrayList<Turma>();
        }
        else{
            this.publicacoesDocente = publicacoes;
        }
        this.objectListView2.setCollection(publicacoesDocente);
    }
    public Collection<? extends Object> getPublicacoesDocente(){
        return this.publicacoesDocente;
    }
    
    public Docente getDocente(){
        return this.docente;
    }
    public void setDocente(Docente docente){
        this.docente = docente;
        this.viewDadosPessoais1.setObject(docente);
    }

    private ObjectListView criarTurmaList() {
        return new ObjectListView(new TurmaViewer());
    }
    private ObjectListView criarListaDePublicacoes(){
        return new ObjectListView();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrVisualizarDados = new javax.swing.JScrollPane();
        pnlVisualizarDadosDocente = new javax.swing.JPanel();
        viewDadosPessoais1 = new br.ufrn.dimap.gui.widgets.ViewDadosPessoais();
        pnlPublicacoes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        objectListView2 = criarListaDePublicacoes();
        pnlMetricas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlTurmasMinistradas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        objectListView1 = criarTurmaList();

        setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, jLabel3.getFont().getSize()+3));
        jLabel3.setText("Publicações");

        jScrollPane1.setViewportView(objectListView2);

        javax.swing.GroupLayout pnlPublicacoesLayout = new javax.swing.GroupLayout(pnlPublicacoes);
        pnlPublicacoes.setLayout(pnlPublicacoesLayout);
        pnlPublicacoesLayout.setHorizontalGroup(
            pnlPublicacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPublicacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlPublicacoesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        pnlPublicacoesLayout.setVerticalGroup(
            pnlPublicacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPublicacoesLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD, jLabel4.getFont().getSize()+3));
        jLabel4.setText("Métricas");

        javax.swing.GroupLayout pnlMetricasLayout = new javax.swing.GroupLayout(pnlMetricas);
        pnlMetricas.setLayout(pnlMetricasLayout);
        pnlMetricasLayout.setHorizontalGroup(
            pnlMetricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMetricasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        pnlMetricasLayout.setVerticalGroup(
            pnlMetricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMetricasLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getStyle() | java.awt.Font.BOLD, jLabel2.getFont().getSize()+3));
        jLabel2.setText("Turmas Ministradas");

        jScrollPane3.setViewportView(objectListView1);

        javax.swing.GroupLayout pnlTurmasMinistradasLayout = new javax.swing.GroupLayout(pnlTurmasMinistradas);
        pnlTurmasMinistradas.setLayout(pnlTurmasMinistradasLayout);
        pnlTurmasMinistradasLayout.setHorizontalGroup(
            pnlTurmasMinistradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTurmasMinistradasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTurmasMinistradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTurmasMinistradasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlTurmasMinistradasLayout.setVerticalGroup(
            pnlTurmasMinistradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTurmasMinistradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlVisualizarDadosDocenteLayout = new javax.swing.GroupLayout(pnlVisualizarDadosDocente);
        pnlVisualizarDadosDocente.setLayout(pnlVisualizarDadosDocenteLayout);
        pnlVisualizarDadosDocenteLayout.setHorizontalGroup(
            pnlVisualizarDadosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisualizarDadosDocenteLayout.createSequentialGroup()
                .addGroup(pnlVisualizarDadosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewDadosPessoais1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlMetricas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlTurmasMinistradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlVisualizarDadosDocenteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlPublicacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlVisualizarDadosDocenteLayout.setVerticalGroup(
            pnlVisualizarDadosDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisualizarDadosDocenteLayout.createSequentialGroup()
                .addComponent(viewDadosPessoais1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMetricas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTurmasMinistradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPublicacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        scrVisualizarDados.setViewportView(pnlVisualizarDadosDocente);

        add(scrVisualizarDados, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private br.ufrn.dimap.gui.widgets.ObjectListView objectListView1;
    private br.ufrn.dimap.gui.widgets.ObjectListView objectListView2;
    private javax.swing.JPanel pnlMetricas;
    private javax.swing.JPanel pnlPublicacoes;
    private javax.swing.JPanel pnlTurmasMinistradas;
    private javax.swing.JPanel pnlVisualizarDadosDocente;
    private javax.swing.JScrollPane scrVisualizarDados;
    private br.ufrn.dimap.gui.widgets.ViewDadosPessoais viewDadosPessoais1;
    // End of variables declaration//GEN-END:variables


}
