/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.widgets;

import br.ufrn.dimap.entidades.Aluno;
import br.ufrn.dimap.gui.ObjectViewer;
import br.ufrn.dimap.entidades.MatriculaAlunoTurma;
import br.ufrn.dimap.entidades.Turma;
import java.awt.Component;

/**
 *
 * @author leobrizolara
 */
public class AlunoTurmaViewer extends javax.swing.JPanel implements ObjectViewer{
    MatriculaAlunoTurma alunoTurma;
    /**
     * Creates new form ViewTurma
     */
    public AlunoTurmaViewer() {
        initComponents();
    }
    

    public void setObject(Object obj) {
        if(obj instanceof MatriculaAlunoTurma){
            this.setMatriculaAlunoTurma((MatriculaAlunoTurma)obj);
        }
    }

    public Object getObject() {
        return getMatriculaAlunoTurma();
    }

    public Class getObjectClass() {
        return MatriculaAlunoTurma.class;
    }
    
    public Component getView() {
        return this;
    }
    public void setMatriculaAlunoTurma(MatriculaAlunoTurma t){
        this.alunoTurma = t;
        update();
    }
    public MatriculaAlunoTurma getMatriculaAlunoTurma(){
        return alunoTurma;
    }
    public void update(){
        if(alunoTurma != null){
            Aluno a = this.alunoTurma.getAluno();
            if(a != null){
                this.lblMatricula.setText(a.getMatricula());
                this.lblNomeAluno.setText(a.getPessoa().getNome());
            }
            lblMedia.setText((alunoTurma.getMedia() != null ? alunoTurma.getMedia().toString() : "-"));
            lblNota1.setText((alunoTurma.getNota(0) != null ? alunoTurma.getNota(0).toString() : "-"));
            lblNota2.setText((alunoTurma.getNota(1) != null ? alunoTurma.getNota(1).toString() : "-"));
            lblNota3.setText((alunoTurma.getNota(2) != null ? alunoTurma.getNota(2).toString() : "-"));
            lblNota4.setText((alunoTurma.getNota(3) != null ? alunoTurma.getNota(3).toString() : "-"));
            
            lblSituacaoAluno.setText(alunoTurma.getSituacao());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatricula = new javax.swing.JLabel();
        lblNomeAluno = new javax.swing.JLabel();
        lblNota1 = new javax.swing.JLabel();
        lblNota2 = new javax.swing.JLabel();
        lblNota3 = new javax.swing.JLabel();
        lblNota4 = new javax.swing.JLabel();
        lblMedia = new javax.swing.JLabel();
        lblSituacaoAluno = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblMatricula.setText("<Matricula>");
        add(lblMatricula);

        lblNomeAluno.setText("<NomeAluno>");
        add(lblNomeAluno);

        lblNota1.setText("<Nota1>");
        add(lblNota1);

        lblNota2.setText("<Nota2>");
        add(lblNota2);

        lblNota3.setText("<Nota3>");
        add(lblNota3);

        lblNota4.setText("<Nota4>");
        add(lblNota4);

        lblMedia.setText("<Media>");
        add(lblMedia);

        lblSituacaoAluno.setText("<Situação Aluno>");
        add(lblSituacaoAluno);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblMedia;
    private javax.swing.JLabel lblNomeAluno;
    private javax.swing.JLabel lblNota1;
    private javax.swing.JLabel lblNota2;
    private javax.swing.JLabel lblNota3;
    private javax.swing.JLabel lblNota4;
    private javax.swing.JLabel lblSituacaoAluno;
    // End of variables declaration//GEN-END:variables

}