/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.widgets;

import br.ufrn.dimap.gui.ObjectViewer;
import br.ufrn.dimap.entidades.Pessoa;
import br.ufrn.dimap.entidades.Vinculo;
import java.awt.Component;

/**
 *
 * @author leobrizolara
 */
public class ViewDadosPessoais extends javax.swing.JPanel implements ObjectViewer {
    private Pessoa pessoa;
    /**
     * Creates new form ViewDadosPessoais
     */
    public ViewDadosPessoais() {
        initComponents();
    }

    public void setObject(Object obj) {
        if(obj instanceof Pessoa){
            this.setPessoa((Pessoa)obj);
        }
        else if(obj instanceof Vinculo){
            Vinculo v = (Vinculo)obj;
            this.setPessoa(v.getPessoa());
        }
    }

    public Object getObject() {
        return getPessoa();
    }

    public Class getObjectClass() {
        return Pessoa.class;
    }
    
    public Component getView() {
        return this;
    }
    
    public void setPessoa(Pessoa pessoa){
        this.pessoa = pessoa;
        this.updateData();
    }
    public Pessoa getPessoa(){
        return this.pessoa;
    }
    public void updateData(){
        if(pessoa != null){
            lblNomeValor.setText(pessoa.getNome());
            lblCidadeValor.setText(pessoa.getCidade());
            lblCpfValor.setText(pessoa.getCpf());
            lblDataDeNascimentoValor.setText(pessoa.getDataNascimento().toString());
            lblEmailValor.setText(pessoa.getEmail());
            lblEnderecoValor.setText(pessoa.getEndereco());
            lblNacionalidadeValor.setText(pessoa.getNacionalidade());
            lblNaturalidadeValor.setText(pessoa.getNaturalidade());
            lblTelefoneValor.setText(pessoa.getTelefone());
            lblUfValor.setText(pessoa.getUf());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDadosPessoais = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCpfLabel = new javax.swing.JLabel();
        lblCpfValor = new javax.swing.JLabel();
        lblNaturalidadeLabel = new javax.swing.JLabel();
        lblNaturalidadeValor = new javax.swing.JLabel();
        lblNacionalidadeLabel = new javax.swing.JLabel();
        lblNacionalidadeValor = new javax.swing.JLabel();
        lblDataDeNascimentoLabel = new javax.swing.JLabel();
        lblDataDeNascimentoValor = new javax.swing.JLabel();
        lblNomeLabel = new javax.swing.JLabel();
        lblNomeValor = new javax.swing.JLabel();
        pnlDadosContato = new javax.swing.JPanel();
        lblTituloContato = new javax.swing.JLabel();
        lblEmailLabel = new javax.swing.JLabel();
        lblEmailValor = new javax.swing.JLabel();
        lblTelefoneLabel = new javax.swing.JLabel();
        lblTelefoneValor = new javax.swing.JLabel();
        pnlDadosEndereco = new javax.swing.JPanel();
        lblTituloEndereco = new javax.swing.JLabel();
        lblUfLabel = new javax.swing.JLabel();
        lblUfValor = new javax.swing.JLabel();
        lblCidadeLabel = new javax.swing.JLabel();
        lblCidadeValor = new javax.swing.JLabel();
        lblEnderecoLabel = new javax.swing.JLabel();
        lblEnderecoValor = new javax.swing.JLabel();
        pnlFoto = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();

        lblTitulo.setFont(lblTitulo.getFont().deriveFont(lblTitulo.getFont().getStyle() | java.awt.Font.BOLD, lblTitulo.getFont().getSize()+3));
        lblTitulo.setText("Dados Pessoais");

        lblCpfLabel.setText("CPF:");

        lblCpfValor.setText("cpfValor");

        lblNaturalidadeLabel.setText("Naturalidade:");

        lblNaturalidadeValor.setText("naturalidadeValor");

        lblNacionalidadeLabel.setText("Nacionalidade:");

        lblNacionalidadeValor.setText("nacionalidadeValor");

        lblDataDeNascimentoLabel.setText("Data De Nascimento:");

        lblDataDeNascimentoValor.setText("DataDeNascimentoValor");

        lblNomeLabel.setText("Nome:");

        lblNomeValor.setText("nomeValor");

        javax.swing.GroupLayout pnlDadosPessoaisLayout = new javax.swing.GroupLayout(pnlDadosPessoais);
        pnlDadosPessoais.setLayout(pnlDadosPessoaisLayout);
        pnlDadosPessoaisLayout.setHorizontalGroup(
            pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(lblCpfLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblCpfValor))
                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(lblNaturalidadeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblNaturalidadeValor))
                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(lblNacionalidadeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblNacionalidadeValor))
                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(lblDataDeNascimentoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblDataDeNascimentoValor))
                    .addGroup(pnlDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(lblNomeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblNomeValor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDadosPessoaisLayout.setVerticalGroup(
            pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosPessoaisLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeLabel)
                    .addComponent(lblNomeValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfLabel)
                    .addComponent(lblCpfValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaturalidadeLabel)
                    .addComponent(lblNaturalidadeValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNacionalidadeLabel)
                    .addComponent(lblNacionalidadeValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDeNascimentoLabel)
                    .addComponent(lblDataDeNascimentoValor))
                .addGap(302, 302, 302))
        );

        lblTituloContato.setFont(lblTituloContato.getFont().deriveFont(lblTituloContato.getFont().getStyle() | java.awt.Font.BOLD, lblTituloContato.getFont().getSize()+3));
        lblTituloContato.setText("Contato");

        lblEmailLabel.setText("Email:");

        lblEmailValor.setText("emailValor");

        lblTelefoneLabel.setText("Telefone:");

        lblTelefoneValor.setText("telefoneValor");

        javax.swing.GroupLayout pnlDadosContatoLayout = new javax.swing.GroupLayout(pnlDadosContato);
        pnlDadosContato.setLayout(pnlDadosContatoLayout);
        pnlDadosContatoLayout.setHorizontalGroup(
            pnlDadosContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloContato)
                    .addGroup(pnlDadosContatoLayout.createSequentialGroup()
                        .addComponent(lblTelefoneLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblTelefoneValor))
                    .addGroup(pnlDadosContatoLayout.createSequentialGroup()
                        .addComponent(lblEmailLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmailValor)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        pnlDadosContatoLayout.setVerticalGroup(
            pnlDadosContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosContatoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTituloContato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailLabel)
                    .addComponent(lblEmailValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneLabel)
                    .addComponent(lblTelefoneValor))
                .addGap(72, 72, 72))
        );

        lblTituloEndereco.setFont(lblTituloEndereco.getFont().deriveFont(lblTituloEndereco.getFont().getStyle() | java.awt.Font.BOLD, lblTituloEndereco.getFont().getSize()+3));
        lblTituloEndereco.setText("Endereço");

        lblUfLabel.setText("UF:");

        lblUfValor.setText("ufValor");

        lblCidadeLabel.setText("Cidade:");

        lblCidadeValor.setText("cidadeValor");

        lblEnderecoLabel.setText("Endereço:");

        lblEnderecoValor.setText("endereçoValor");

        javax.swing.GroupLayout pnlDadosEnderecoLayout = new javax.swing.GroupLayout(pnlDadosEndereco);
        pnlDadosEndereco.setLayout(pnlDadosEnderecoLayout);
        pnlDadosEnderecoLayout.setHorizontalGroup(
            pnlDadosEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloEndereco)
                    .addGroup(pnlDadosEnderecoLayout.createSequentialGroup()
                        .addComponent(lblEnderecoLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblEnderecoValor))
                    .addGroup(pnlDadosEnderecoLayout.createSequentialGroup()
                        .addComponent(lblCidadeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblCidadeValor))
                    .addGroup(pnlDadosEnderecoLayout.createSequentialGroup()
                        .addComponent(lblUfLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lblUfValor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDadosEnderecoLayout.setVerticalGroup(
            pnlDadosEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosEnderecoLayout.createSequentialGroup()
                .addComponent(lblTituloEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUfLabel)
                    .addComponent(lblUfValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCidadeLabel)
                    .addComponent(lblCidadeValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnderecoLabel)
                    .addComponent(lblEnderecoValor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFoto.setText("foto");
        lblFoto.setPreferredSize(new java.awt.Dimension(135, 160));

        javax.swing.GroupLayout pnlFotoLayout = new javax.swing.GroupLayout(pnlFoto);
        pnlFoto.setLayout(pnlFotoLayout);
        pnlFotoLayout.setHorizontalGroup(
            pnlFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoLayout.createSequentialGroup()
                .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlFotoLayout.setVerticalGroup(
            pnlFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDadosPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDadosEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDadosContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDadosContato, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDadosEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCidadeLabel;
    private javax.swing.JLabel lblCidadeValor;
    private javax.swing.JLabel lblCpfLabel;
    private javax.swing.JLabel lblCpfValor;
    private javax.swing.JLabel lblDataDeNascimentoLabel;
    private javax.swing.JLabel lblDataDeNascimentoValor;
    private javax.swing.JLabel lblEmailLabel;
    private javax.swing.JLabel lblEmailValor;
    private javax.swing.JLabel lblEnderecoLabel;
    private javax.swing.JLabel lblEnderecoValor;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNacionalidadeLabel;
    private javax.swing.JLabel lblNacionalidadeValor;
    private javax.swing.JLabel lblNaturalidadeLabel;
    private javax.swing.JLabel lblNaturalidadeValor;
    private javax.swing.JLabel lblNomeLabel;
    private javax.swing.JLabel lblNomeValor;
    private javax.swing.JLabel lblTelefoneLabel;
    private javax.swing.JLabel lblTelefoneValor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloContato;
    private javax.swing.JLabel lblTituloEndereco;
    private javax.swing.JLabel lblUfLabel;
    private javax.swing.JLabel lblUfValor;
    private javax.swing.JPanel pnlDadosContato;
    private javax.swing.JPanel pnlDadosEndereco;
    private javax.swing.JPanel pnlDadosPessoais;
    private javax.swing.JPanel pnlFoto;
    // End of variables declaration//GEN-END:variables


}
