/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.widgets;

import br.ufrn.dimap.entidades.Publicacao;
import java.awt.Component;

/**
 *
 * @author leobrizolara
 */
public class PublicacoesViewer extends javax.swing.JPanel implements ObjectViewer {
    Publicacao publicacao;
    /**
     * Creates new form PublicacoesViewer
     */
    public PublicacoesViewer() {
        initComponents();
    }

    public void setObject(Object obj) {
        if(obj instanceof Publicacao){
            setPublicacao((Publicacao)obj);
        }
    }

    public Object getObject() {
        return getPublicacao();
    }
    public Class getObjectClass() {
        return Publicacao.class;
    }
    
    public void setPublicacao(Publicacao publicacao){
        this.publicacao = publicacao;
        
        this.lblTituloValor.setText(publicacao.getTitulo());
        this.lblTemaValor.setText(publicacao.getTema());
        this.lblDataValor.setText(publicacao.getData().toString());
        this.lblIssnValor.setText(publicacao.getIssn());
        this.lblPeriodicoValor.setText(publicacao.getPeriodico());
        this.lblTipoValor.setText(publicacao.getTipo());
        this.lblUrlValor.setText(publicacao.getUrl());
        this.txtResumo.setText(publicacao.getResumo());
    }
    public Publicacao getPublicacao(){
        return this.publicacao;
    }

    public Component getView() {
        return this;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtResumo = new javax.swing.JTextArea();
        lblTituloValor = new javax.swing.JLabel();
        lblTemaLabel = new javax.swing.JLabel();
        lblTemaValor = new javax.swing.JLabel();
        lblTipoLabel = new javax.swing.JLabel();
        lblTipoValor = new javax.swing.JLabel();
        lblPeriodicoLabel = new javax.swing.JLabel();
        lblPeriodicoValor = new javax.swing.JLabel();
        lblDataLabel = new javax.swing.JLabel();
        lblDataValor = new javax.swing.JLabel();
        lblIssnLabel = new javax.swing.JLabel();
        lblIssnValor = new javax.swing.JLabel();
        lblUrlLabel = new javax.swing.JLabel();
        lblUrlValor = new javax.swing.JLabel();
        lblResumoLabel = new javax.swing.JLabel();

        txtResumo.setColumns(20);
        txtResumo.setRows(5);
        jScrollPane1.setViewportView(txtResumo);

        lblTituloValor.setFont(lblTituloValor.getFont().deriveFont(lblTituloValor.getFont().getSize()+4f));
        lblTituloValor.setText("< Titulo >");

        lblTemaLabel.setText("Tema:");

        lblTemaValor.setText("< tema >");

        lblTipoLabel.setText("Tipo de publicação:");

        lblTipoValor.setText("< tipo >");

        lblPeriodicoLabel.setText("Periódico:");

        lblPeriodicoValor.setText("< periodico >");

        lblDataLabel.setText("Data de publicação: ");

        lblDataValor.setText("< data >");

        lblIssnLabel.setText("ISSN:");

        lblIssnValor.setText("< issn >");

        lblUrlLabel.setText("URL:");

        lblUrlValor.setText("< url >");

        lblResumoLabel.setText("Resumo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTituloValor)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTemaLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTemaValor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPeriodicoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPeriodicoValor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDataLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDataValor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblIssnLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblIssnValor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUrlLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblUrlValor)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResumoLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTipoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTipoValor)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloValor)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemaLabel)
                    .addComponent(lblTemaValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoLabel)
                    .addComponent(lblTipoValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeriodicoLabel)
                    .addComponent(lblPeriodicoValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataLabel)
                    .addComponent(lblDataValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIssnLabel)
                    .addComponent(lblIssnValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUrlLabel)
                    .addComponent(lblUrlValor))
                .addGap(18, 18, 18)
                .addComponent(lblResumoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataLabel;
    private javax.swing.JLabel lblDataValor;
    private javax.swing.JLabel lblIssnLabel;
    private javax.swing.JLabel lblIssnValor;
    private javax.swing.JLabel lblPeriodicoLabel;
    private javax.swing.JLabel lblPeriodicoValor;
    private javax.swing.JLabel lblResumoLabel;
    private javax.swing.JLabel lblTemaLabel;
    private javax.swing.JLabel lblTemaValor;
    private javax.swing.JLabel lblTipoLabel;
    private javax.swing.JLabel lblTipoValor;
    private javax.swing.JLabel lblTituloValor;
    private javax.swing.JLabel lblUrlLabel;
    private javax.swing.JLabel lblUrlValor;
    private javax.swing.JTextArea txtResumo;
    // End of variables declaration//GEN-END:variables

}
