/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.dimap.gui.widgets;

import br.ufrn.dimap.gui.ObjectViewer;
import br.ufrn.dimap.entidades.MatriculaAlunoTurma;
import br.ufrn.dimap.entidades.Turma;
import java.awt.Component;

/**
 *
 * @author leobrizolara
 */
public class TurmaAlunoViewer extends javax.swing.JPanel implements ObjectViewer{
    MatriculaAlunoTurma alunoTurma;
    /**
     * Creates new form ViewTurma
     */
    public TurmaAlunoViewer() {
        initComponents();
    }
    

    public void setObject(Object obj) {
        if(obj instanceof MatriculaAlunoTurma){
            this.setMatriculaAlunoTurma((MatriculaAlunoTurma)obj);
        }
    }

    public Object getObject() {
        return getMatriculaAlunoTurma();
    }

    public Class getObjectClass() {
        return MatriculaAlunoTurma.class;
    }
    
    public Component getView() {
        return this;
    }
    public void setMatriculaAlunoTurma(MatriculaAlunoTurma t){
        this.alunoTurma = t;
        update();
    }
    public MatriculaAlunoTurma getMatriculaAlunoTurma(){
        return alunoTurma;
    }
    public void update(){
        if(alunoTurma != null){
            Turma t = this.alunoTurma.getTurma();
            if(t != null){
                this.lblNumTurma.setText(Integer.toString(t.getNumeroTurma()));
                this.lblPeriodo.setText(t.getPeriodoLetivo());
                this.lblDisciplina.setText(
                        (t.getDisciplina() != null ? t.getDisciplina().getNome() : "") );
                
            }
            this.lblSituacaoTurma.setText(alunoTurma.getSituacao());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDisciplina = new javax.swing.JLabel();
        lblPeriodo = new javax.swing.JLabel();
        lblNumTurma = new javax.swing.JLabel();
        lblSituacaoTurma = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        lblDisciplina.setText("<Disciplina>");
        add(lblDisciplina);

        lblPeriodo.setText("<Período>");
        add(lblPeriodo);

        lblNumTurma.setText("<Num Turma>");
        add(lblNumTurma);

        lblSituacaoTurma.setText("<Situação Aluno>");
        add(lblSituacaoTurma);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDisciplina;
    private javax.swing.JLabel lblNumTurma;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblSituacaoTurma;
    // End of variables declaration//GEN-END:variables

}